import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios';

const initialState = {
  selectedShow: '',
  seatDetails:[],
  selectedSeats:null
};

export const getSeatsForTheSelectedShow = createAsyncThunk(
    'getSeatsForTheSelectedShow',
    async (data) => {
    console.log(data);
    // console.log(data.movieID);
    const url = `/getSeatsForTheSelectedShow/${data}`;
    console.log(url);
    const response = await axios.get(url);
    console.log(response);
    return response;
    }
);

  
export const bookSeats = createAsyncThunk(
    'bookSeats',
    async (data) => {
    console.log(data);
    // console.log(data.movieID);
    data.forEach(async (element) => {
        const url = `/bookSeat/${element}`;
        console.log(url);
        const response = await axios.get(url);
        console.log(response);
    // return response;
    });
    // const url = `/bookSeats/${data}`;
    // console.log(url);
    // const response = await axios.get(url);
    // console.log(response);
    // return response;
    return "success";
    }
);

  
export const seatBookingReducer = createSlice({
  name: 'city',
  initialState,
  reducers: {
    selectTheatreHall: (state, action) => {
      state.selectedTheatreHall = action.payload;
    },  
    setSelectedSeatsAsync: (state, action) => {
      state.selectedSeats = action.payload;
    }  
  },
  // The `reducers` field lets us define reducers and generate associated actions
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getSeatsForTheSelectedShow.fulfilled, (state, action) => {
        state.seatDetails = action.payload.data.data[0].Seats;
        state.selectedShow = action.payload.data.data[0];
      });
  },
});

export const { selectTheatreHall, setSelectedSeatsAsync } = seatBookingReducer.actions;
export const selectedShow = (state) => state.seatBoooking.selectedShow;
export const seatDetails = (state) => state.seatBoooking.seatDetails;
export const selectedSeats = (state) => state.seatBoooking.selectedSeats;

export default seatBookingReducer.reducer;
