import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios';

const initialState = {
  theatreHalls: [],
  selectedTheatreHall: ''
};

export const getTheatresForSelectedMovie = createAsyncThunk(
    'getTheatresForSelectedMovie',
    async (data) => {
    console.log(data.cityID);
    console.log(data.movieID);
    const url = `/getTheatresForSelectedMovie/${data.cityID}/${data.movieID}`;
    console.log(url);
    const response = await axios.get(url);
    console.log(response);
    return response;
    }
);

  
export const theatreHallSlice = createSlice({
  name: 'city',
  initialState,
  reducers: {
    selectTheatreHall: (state, action) => {
      state.selectedTheatreHall = action.payload;
    }  
  },
  // The `reducers` field lets us define reducers and generate associated actions
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getTheatresForSelectedMovie.fulfilled, (state, action) => {
        state.theatreHalls = action.payload.data.data;
      });
  },
});

export const { selectTheatreHall } = theatreHallSlice.actions;
export const theatreHalls = (state) => state.theatreHall.theatreHalls;

export default theatreHallSlice.reducer;
